# python train.py --d train_data --m vae --e 5 -t y
model:
  backbone: inceptionnext_small
  embedder: vit_base_patch16_224
  latent_dims: 12544

batch_size: 64
epoch: 1
learning_rate: 0.0001
weight_decay: 0.0001
num_classes: 2
img_size: 224
min_val_loss: 10000
